@startuml overview
!define AzurePuml https://raw.githubusercontent.com/travisnielsen/Azure-PlantUML/release/3-0/dist
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Compute/APIManagementServices.puml
!includeurl AzurePuml/Compute/WebApp.puml
!includeurl AzurePuml/Compute/FunctionApps.puml
!includeurl AzurePuml/Integration/ServiceBus.puml
!includeurl AzurePuml/Integration/EventHubs.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml


LAYOUT_LEFT_RIGHT

title Application Overview

Entity user

' AzureActiveDirectory(aad, "OAuth", "API scopes and authorizations")

Container(web, "Web Client", "ReactJS 16.13.x", "User identity and interface")

APIManagementServices(apim, "API gateway", "Managed Identity / Client Certificate", "Validate OAuth tokens and perform access control checks.")
Container(ordersvc, "Order Service", "JRE11 - Spring Boot 2.3.x", "Create and read orders. Process fulfillment stautus")
Container(inventorysvc, "Inventory Service", "JRE11 - Spring Boot 2.3.x", "")
FunctionApps(deliverysvc, "Delivery", "NodeJS 12.13.1", "")

EventHubs(eh, "Fulfillment stream", "")
ServiceBus(sb, "Message broker", "Standard SKU", "topics: orders, fulfillment")

AzureCosmosDB(orderdb, "Orders", "400 RUs (autoscale to 4000)", "Order with current aggregate status")

Rel(web, apim, "Create order")
Rel(apim, ordersvc, "Create order" )
Rel(ordersvc, inventorysvc, "Check / reserve inventory")
Rel(ordersvc, sb, "Create order")
Rel(ordersvc, orderdb, "Updates order state")
Rel_Back(inventorysvc, sb, "Receive order")
Rel_Back(deliverysvc, sb, "Receive order")
Rel(eh, deliverysvc, "fulfillment stream")

user -> web

deliverysvc --> sb : "Fulfillment update event"
ordersvc <-- sb : "Get fulfillment updates"

' Rel(func1, aad, "1. Request Access Token\nManaged Identity\nResource: api://orders")
' Rel_Back(func1, aad, "2. Access Token\naud:api://orders\nroles: [orders.read]")
' Rel(func1, apim, "3. Request order status\nAccess Token")
' Rel(apim, aad, "4. Validate token")
' Rel_Back(func2, apim, "5. Proxied call\nAPIM client cert\nor\nAPIM Managed Instance token")

@end